language: python
python: 2.6
dist: trusty
matrix:
  - python: 2.6
    env: TEST_ID=1 DMTCP_VERSION=2.5.1
  - python: 2.6
    env: TEST_ID=2 DMTCP_VERSION=2.5.1
  - python: 2.6
    env: TEST_ID=3 DMTCP_VERSION=2.5.1
  - python: 2.6
    env: TEST_ID=4 DMTCP_VERSION=2.5.1
  - python: 2.6
    env: TEST_ID=5 DMTCP_VERSION=2.5.1
  - python: 2.7
    env: TEST_ID=1 DMTCP_VERSION=2.5.1
  - python: 2.7
    env: TEST_ID=2 DMTCP_VERSION=2.5.1
  - python: 2.7
    env: TEST_ID=3 DMTCP_VERSION=2.5.1
  - python: 2.7
    env: TEST_ID=4 DMTCP_VERSION=2.5.1
  - python: 2.7
    env: TEST_ID=5 DMTCP_VERSION=2.5.1
  - python: 2.7
    dist: xenial
    env: TEST_ID=1 DMTCP_VERSION=2.5.1
  - python: 2.7
    dist: xenial
    env: TEST_ID=2 DMTCP_VERSION=2.5.1
  - python: 2.7
    dist: xenial
    env: TEST_ID=3 DMTCP_VERSION=2.5.1
  - python: 2.7
    dist: xenial
    env: TEST_ID=4 DMTCP_VERSION=2.5.1
  - python: 2.7
    dist: xenial
    env: TEST_ID=5 DMTCP_VERSION=2.5.1
addons:
  apt:
    packages:
      # 'lockfile' command is provided by procmail package (yes...)
      - procmail
env:
    - DMTCP_VERSION=2.5.1
before_install:
    # download & build DMTCP
    - wget https://github.com/dmtcp/dmtcp/archive/${DMTCP_VERSION}.tar.gz
    - mkdir -p $PWD/DMTCP-${DMTCP_VERSION}
    - tar xfz ${DMTCP_VERSION}.tar.gz -C $PWD/DMTCP-${DMTCP_VERSION} --strip-components 1
    - cd DMTCP-${DMTCP_VERSION} && ./configure --prefix $TRAVIS_BUILD_DIR && make && make check && make install && cd -
install:
    # make sure DMTCP command and fake 'qsub' command is available
    - export PATH=$TRAVIS_BUILD_DIR/bin:$PWD/test:$PATH
    # generate 'csub' script
    - ./makecsub.py
script:
    - $PWD/test/test.sh
